format = """
[](fg:#cdb190 bg:none)\
[  ペンギン](fg:#000000 bg:#cdb190)\
[ ](fg:#cdb190 bg:#453636)\
[𝖗𝖆𝖓𝖌𝖊𝖗 ](fg:#ea6151 bg:#453636)\
[ ](fg:#453636 bg:#ea6151)\
[ ](fg:#ea6151 bg:none)\
$directory\
[](fg:#B4B4B4)\
$git_branch\
$git_status\
[](fg:#B4B4B4)\
$nodejs\
$rust\
$golang\
$php\
$elixir\
$python\
$c\
$java
[](fg:#B4B4B4)\ 
[](fg:#B4B4B4)\ 
[ $fill](fg:#B4B4B4)[](#B4B4B4)$time\
[](#ffffff)\ 
\n$character"""

[directory]
style = '#B4B4B4'
format = "[ $path]($style)"
truncation_length = 3
truncation_symbol = ""

[directory.substitutions]
"/home/ranger/ranger097_nixos_dotfiles/hypr/hyprland.conf" = " HYPRLAND.CONF"
"/home/ranger/ranger097_nixos_dotfiles/hypr/hypridle.conf" = " HYPRIDLE.CONF"
"/home/ranger/ranger097_nixos_dotfiles/hypr/hyprlock.conf" = " HYPRLOCK.CONF"
"/home/ranger/ranger097_nixos_dotfiles/hypr/hyprsunset.conf" = " HYPRSUNSET.CONF"
"/home/ranger/ranger097_nixos_dotfiles/bash.nix" = " BASH.NIX"
"/home/ranger/ranger097_nixos_dotfiles/configuration.nix" = " CONFIGURATION.NIX"
"/home/ranger/ranger097_nixos_dotfiles/cosmic.nix" = " COSMIC.NIX"
"/home/ranger/ranger097_nixos_dotfiles/flake.nix" = " FLAKE.NIX"
"/home/ranger/ranger097_nixos_dotfiles/home.nix" = " HOME.NIX"
"/home/ranger/ranger097_nixos_dotfiles/hyprland.nix" = " HYPRLAND.NIX"
"/home/ranger/ranger097_nixos_dotfiles/shell.nix" = " SHELL.NIX"
"/home/ranger/ranger097_nixos_dotfiles/packages.nix" = " PACKAGES.NIX"
"/home/ranger/ranger097_nixos_dotfiles/starship" = " STARSHIP CONFIG"
"/home/ranger/ranger097_nixos_dotfiles/ghostty" = " GHOSTTY"
"/home/ranger/ranger097_nixos_dotfiles/kvantum" = " KVANTUM"
"/home/ranger/ranger097_nixos_dotfiles/waybar" = "   WAYBAR"
"/home/ranger/ranger097_nixos_dotfiles/rofi" = "   ROFI"
"/home/ranger/ranger097_nixos_dotfiles/wallpapers" = "   WALLPAPERS"
"/home/ranger/ranger097_nixos_dotfiles/hypr" = " HYPRLAND"
"/home/ranger/ranger097_nixos_dotfiles/wlogout" = " WLOGOUT"
"/home/ranger/ranger097_nixos_dotfiles" = " NIXOS CONFIGS"
"/home/ranger/Projects" = "  CODING PROJECTS"
"~/.config" = " CONFIGS"
"Documents" = "   DOCUMENTS"
"Downloads" = " DOWNLOADS"
"Music" = " MUSIC"
"Pictures" = " PICTURE"
"Home" = " HOME"
"~" = " "


[git_branch]
symbol = ""
style = '#B4B4B4'
format = '[[ $symbol $branch ](#909090)]($style)'

[git_status]
style = '#B4B4B4'
format = '[[($all_status$ahead_behind)](fg:#909090)]($style)'

[nodejs]
symbol = ""
style = "bg:#000000"
format = '[[ $symbol ($version) ](fg:#C83C3C bg:#000000)]($style)'

[rust]
symbol = ""
style = "bg:#000000"
format = '[[ $symbol ($version) ](fg:#C83C3C bg:#000000)]($style)'

[golang]
symbol = "󰟓"
style = "bg:#000000"
format = '[[ $symbol ($version) ](fg:#C83C3C bg:#000000)]($style)'

[elixir]
symbol = ""
style = "bg:#000000"
format = '[[ $symbol ($version) ](fg:#C83C3C bg:#000000)]($style)'

[java]
symbol = ""
style = "bg:#000000"
format = '[[ $symbol ($version) ](fg:#C83C3C bg:#000000)]($style)'

[python]
symbol = ""
style = "bg:#000000"
format = '[[ $symbol ($version) ](fg:#C83C3C bg:#000000)]($style)'

[c]
symbol = ""
style = "bg:#000000"
format = '[[ $symbol ($version) ](fg:#C83C3C bg:#000000)]($style)'

[fill]
symbol = " "
style = "fg:#B4B4B4" 

[time]
disabled = true
time_format = "%R" # Hour:Minute Format
style = "bg:#1d2230"
format = '[[ $time](fg:#CAAE48)]($style)'

[character]
format = ''
