format = """
[󰟒 ](fg:#bcbcbc bg:none)\
$directory\
$git_branch\
$git_status\
$nodejs\
$rust\
$golang\
$elixir\
$python\
$cpp\
$java\
\n$character\
\n"""

[directory]
style = '#CECFD1'
format = "[$path]($style)"
truncation_length = 8
truncation_symbol = ""
truncate_to_repo = false

[directory.substitutions]
"/ranger097_nixos_dotfiles" = "  dotfiles "
"/Projects/go_projects" = "  Projects  go_projects "
"/Projects/cplusplus_projects" = "  Projects  cplusplus_projects "
"/Projects/elixir_projects" = "  Projects  elixir_projects "
"/Projects/java_projects" = "  Projects  java_projects "
"/Projects/python_projects" = "  Projects  python_projects " 
"/Projects/rust_projects" = "  Projects  rust_projects "
"/hypr" = "  hypr" 


"Documents" = " 󰣞 documents"
"Downloads" = " 󰉍 downloads"
"Music" = " 󱍙 music"
"Pictures" = " 󰉏 pictures"
"~" = "home"
"^/" = ""
"/" = ""

[direnv]
disabled = false
detect_files = ['.envrc']
allowed_msg = "allowed"
not_allowed_msg = "not allowed"
denied_msg = "denied"
loaded_msg = "loaded"
unloaded_msg = "not loaded"

[git_branch]
symbol = ""
style = "#bcbcbc"
format = '[[on $symbol $branch ](fg:#bcbcbc)]($style)'

[git_status]
style = '#bcbcbc'
format = '[[($all_status$ahead_behind)](fg:#bcbcbc)]($style)'

[nodejs]
symbol = ""
style = "bg:#000000"
format = '[[$symbol ($version) ](fg:#C83C3C bg:#000000)]($style)'

[rust]
symbol = ""
style = "bg:#000000"
format = '[[$symbol ($version) ](fg:#C83C3C bg:#000000)]($style)'

[golang]
symbol = ""
style = "bg:#000000"
format = '[[$symbol ($version) ](fg:#C83C3C bg:#000000)]($style)'

[elixir]
symbol = ""
style = "bg:#000000"
format = '[[$symbol ($version) ](fg:#C83C3C bg:#000000)]($style)'

[java]
symbol = ""
style = "bg:#000000"
format = '[[$symbol ($version) ](fg:#C83C3C bg:#000000)]($style)'

[python]
symbol = ""
style = "bg:#000000"
format = '[[$symbol ($version) ](fg:#C83C3C bg:#000000)]($style)'

[cpp]
symbol = ""
style = "bg:#000000"
format = '[[$symbol ($version) ](fg:#C83C3C bg:#000000)]($style)'

[fill]
symbol = "─"
style = "fg:#404040" 

[time]
disabled = true
time_format = "%R" # Hour:Minute Format
style = "bg:#1d2230"
format = '[[$time](fg:#CAAE48)]($style)'

[character]
format = "[󰳟 ](fg:#bcbcbc bg:#none)"
