format = """
[󱂵 ](fg:#707070 bg:none)\
$directory\
[](fg:#505050)\
$git_branch\
$git_status\
[](fg:#505050)\
$nodejs\
$rust\
$golang\
$php\
$elixir\
$python\
$cpp\
$java\
\n$fill\
\n$character"""

[directory]
style = '#707070'
format = "[$path]($style)"
truncation_length = 8
truncation_symbol = ""
truncate_to_repo = false

[directory.substitutions]
"/ranger097_nixos_dotfiles" = "  dotfiles "
"/Projects/go_projects" = "  Projects  go_projects "
"/Projects/cplusplus_projects" = "  Projects  cplusplus_projects "
"/Projects/elixir_projects" = "  Projects  elixir_projects "
"/Projects/java_projects" = "  Projects  java_projects "
"/Projects/python_projects" = "  Projects  python_projects " 
"/Projects/rust_projects" = "  Projects  rust_projects "
"/hypr" = "  hypr" 


"Documents" = " 󰣞 documents"
"Downloads" = " 󰉍 downloads"
"Music" = " 󱍙 music"
"Pictures" = " 󰉏 pictures"
"~" = "home"
"^/" = ""
"/" = ""

[direnv]
disabled = false
detect_files = ['.envrc']
allowed_msg = "allowed"
not_allowed_msg = "not allowed"
denied_msg = "denied"
loaded_msg = "loaded"
unloaded_msg = "not loaded"

[git_branch]
symbol = ""
style = "#808080"
format = '[[on $symbol $branch ](#69491D)]($style)'

[git_status]
style = '#505050'
format = '[[($all_status$ahead_behind)](fg:#909090)]($style)'

[nodejs]
symbol = ""
style = "bg:#000000"
format = '[[$symbol ($version) ](fg:#C83C3C bg:#000000)]($style)'

[rust]
symbol = ""
style = "bg:#000000"
format = '[[$symbol ($version) ](fg:#C83C3C bg:#000000)]($style)'

[golang]
symbol = ""
style = "bg:#000000"
format = '[[$symbol ($version) ](fg:#C83C3C bg:#000000)]($style)'

[elixir]
symbol = ""
style = "bg:#000000"
format = '[[$symbol ($version) ](fg:#C83C3C bg:#000000)]($style)'

[java]
symbol = ""
style = "bg:#000000"
format = '[[$symbol ($version) ](fg:#C83C3C bg:#000000)]($style)'

[python]
symbol = ""
style = "bg:#000000"
format = '[[$symbol ($version) ](fg:#C83C3C bg:#000000)]($style)'

[cpp]
symbol = ""
style = "bg:#000000"
format = '[[$symbol ($version) ](fg:#C83C3C bg:#000000)]($style)'

[fill]
symbol = "─"
style = "fg:#B4B4B4" 

[time]
disabled = true
time_format = "%R" # Hour:Minute Format
style = "bg:#1d2230"
format = '[[$time](fg:#CAAE48)]($style)'

[character]
format = "[󱞪](fg:#69491D) "
